// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: telemetry.proto
// Protobuf C++ Version: 5.29.1

#include "telemetry.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protoFirst {

inline constexpr Telemetry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sender_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        x_{0},
        y_{0},
        s_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Telemetry::Telemetry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TelemetryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TelemetryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TelemetryDefaultTypeInternal() {}
  union {
    Telemetry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TelemetryDefaultTypeInternal _Telemetry_default_instance_;
}  // namespace protoFirst
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_telemetry_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_telemetry_2eproto = nullptr;
const ::uint32_t
    TableStruct_telemetry_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _impl_.sender_name_),
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::protoFirst::Telemetry, _impl_.s_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::protoFirst::Telemetry)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protoFirst::_Telemetry_default_instance_._instance,
};
const char descriptor_table_protodef_telemetry_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017telemetry.proto\022\nprotoFirst\"A\n\tTelemet"
    "ry\022\023\n\013sender_name\030\001 \002(\t\022\t\n\001x\030\002 \001(\005\022\t\n\001y\030"
    "\003 \001(\005\022\t\n\001s\030\004 \001(\005"
};
static ::absl::once_flag descriptor_table_telemetry_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_telemetry_2eproto = {
    false,
    false,
    96,
    descriptor_table_protodef_telemetry_2eproto,
    "telemetry.proto",
    &descriptor_table_telemetry_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_telemetry_2eproto::offsets,
    file_level_enum_descriptors_telemetry_2eproto,
    file_level_service_descriptors_telemetry_2eproto,
};
namespace protoFirst {
// ===================================================================

class Telemetry::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Telemetry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Telemetry, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

Telemetry::Telemetry(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protoFirst.Telemetry)
}
inline PROTOBUF_NDEBUG_INLINE Telemetry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protoFirst::Telemetry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sender_name_(arena, from.sender_name_) {}

Telemetry::Telemetry(
    ::google::protobuf::Arena* arena,
    const Telemetry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Telemetry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, x_),
           offsetof(Impl_, s_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::s_));

  // @@protoc_insertion_point(copy_constructor:protoFirst.Telemetry)
}
inline PROTOBUF_NDEBUG_INLINE Telemetry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        sender_name_(arena) {}

inline void Telemetry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, s_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::s_));
}
Telemetry::~Telemetry() {
  // @@protoc_insertion_point(destructor:protoFirst.Telemetry)
  SharedDtor(*this);
}
inline void Telemetry::SharedDtor(MessageLite& self) {
  Telemetry& this_ = static_cast<Telemetry&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Telemetry::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Telemetry(arena);
}
constexpr auto Telemetry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Telemetry),
                                            alignof(Telemetry));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Telemetry::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Telemetry_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        Telemetry::IsInitializedImpl,
        &Telemetry::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Telemetry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Telemetry::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Telemetry>(), &Telemetry::ByteSizeLong,
            &Telemetry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Telemetry, _impl_._cached_size_),
        false,
    },
    &Telemetry::kDescriptorMethods,
    &descriptor_table_telemetry_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Telemetry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 40, 2> Telemetry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Telemetry, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protoFirst::Telemetry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 s = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Telemetry, _impl_.s_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.s_)}},
    // required string sender_name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.sender_name_)}},
    // optional int32 x = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Telemetry, _impl_.x_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.x_)}},
    // optional int32 y = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Telemetry, _impl_.y_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string sender_name = 1;
    {PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.sender_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 x = 2;
    {PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.x_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 y = 3;
    {PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.y_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 s = 4;
    {PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.s_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\24\13\0\0\0\0\0\0"
    "protoFirst.Telemetry"
    "sender_name"
  }},
};

PROTOBUF_NOINLINE void Telemetry::Clear() {
// @@protoc_insertion_point(message_clear_start:protoFirst.Telemetry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.sender_name_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000000eu) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.s_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.s_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Telemetry::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Telemetry& this_ = static_cast<const Telemetry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Telemetry::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Telemetry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protoFirst.Telemetry)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required string sender_name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_sender_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "protoFirst.Telemetry.sender_name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional int32 x = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_x(), target);
          }

          // optional int32 y = 3;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_y(), target);
          }

          // optional int32 s = 4;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_s(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protoFirst.Telemetry)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Telemetry::ByteSizeLong(const MessageLite& base) {
          const Telemetry& this_ = static_cast<const Telemetry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Telemetry::ByteSizeLong() const {
          const Telemetry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protoFirst.Telemetry)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // required string sender_name = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sender_name());
            }
          }
          if (cached_has_bits & 0x0000000eu) {
            // optional int32 x = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_x());
            }
            // optional int32 y = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_y());
            }
            // optional int32 s = 4;
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_s());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Telemetry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Telemetry*>(&to_msg);
  auto& from = static_cast<const Telemetry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protoFirst.Telemetry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_sender_name(from._internal_sender_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.s_ = from._impl_.s_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Telemetry::CopyFrom(const Telemetry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoFirst.Telemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Telemetry::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Telemetry&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void Telemetry::InternalSwap(Telemetry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_name_, &other->_impl_.sender_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.s_)
      + sizeof(Telemetry::_impl_.s_)
      - PROTOBUF_FIELD_OFFSET(Telemetry, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Telemetry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protoFirst
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_telemetry_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
