// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

#include "info.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace info {

inline constexpr generic_message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : authorname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contents_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR generic_message::generic_message(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct generic_messageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR generic_messageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~generic_messageDefaultTypeInternal() {}
  union {
    generic_message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 generic_messageDefaultTypeInternal _generic_message_default_instance_;
}  // namespace info
static ::_pb::Metadata file_level_metadata_info_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_info_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_info_2eproto = nullptr;
const ::uint32_t TableStruct_info_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::info::generic_message, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::info::generic_message, _impl_.authorname_),
    PROTOBUF_FIELD_OFFSET(::info::generic_message, _impl_.contents_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::info::generic_message)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::info::_generic_message_default_instance_._instance,
};
const char descriptor_table_protodef_info_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\ninfo.proto\022\004info\"7\n\017generic_message\022\022\n"
    "\nauthorName\030\001 \001(\t\022\020\n\010contents\030\002 \001(\tb\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_info_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_info_2eproto = {
    false,
    false,
    83,
    descriptor_table_protodef_info_2eproto,
    "info.proto",
    &descriptor_table_info_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_info_2eproto::offsets,
    file_level_metadata_info_2eproto,
    file_level_enum_descriptors_info_2eproto,
    file_level_service_descriptors_info_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_info_2eproto_getter() {
  return &descriptor_table_info_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_info_2eproto(&descriptor_table_info_2eproto);
namespace info {
// ===================================================================

class generic_message::_Internal {
 public:
};

generic_message::generic_message(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:info.generic_message)
}
inline PROTOBUF_NDEBUG_INLINE generic_message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : authorname_(arena, from.authorname_),
        contents_(arena, from.contents_),
        _cached_size_{0} {}

generic_message::generic_message(
    ::google::protobuf::Arena* arena,
    const generic_message& from)
    : ::google::protobuf::Message(arena) {
  generic_message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:info.generic_message)
}
inline PROTOBUF_NDEBUG_INLINE generic_message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : authorname_(arena),
        contents_(arena),
        _cached_size_{0} {}

inline void generic_message::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
generic_message::~generic_message() {
  // @@protoc_insertion_point(destructor:info.generic_message)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void generic_message::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.authorname_.Destroy();
  _impl_.contents_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void generic_message::Clear() {
// @@protoc_insertion_point(message_clear_start:info.generic_message)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.authorname_.ClearToEmpty();
  _impl_.contents_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* generic_message::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> generic_message::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_generic_message_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string contents = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(generic_message, _impl_.contents_)}},
    // string authorName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(generic_message, _impl_.authorname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string authorName = 1;
    {PROTOBUF_FIELD_OFFSET(generic_message, _impl_.authorname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string contents = 2;
    {PROTOBUF_FIELD_OFFSET(generic_message, _impl_.contents_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\12\10\0\0\0\0\0"
    "info.generic_message"
    "authorName"
    "contents"
  }},
};

::uint8_t* generic_message::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:info.generic_message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string authorName = 1;
  if (!this->_internal_authorname().empty()) {
    const std::string& _s = this->_internal_authorname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "info.generic_message.authorName");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string contents = 2;
  if (!this->_internal_contents().empty()) {
    const std::string& _s = this->_internal_contents();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "info.generic_message.contents");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:info.generic_message)
  return target;
}

::size_t generic_message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:info.generic_message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string authorName = 1;
  if (!this->_internal_authorname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_authorname());
  }

  // string contents = 2;
  if (!this->_internal_contents().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_contents());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData generic_message::_class_data_ = {
    generic_message::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* generic_message::GetClassData() const {
  return &_class_data_;
}

void generic_message::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<generic_message*>(&to_msg);
  auto& from = static_cast<const generic_message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:info.generic_message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_authorname().empty()) {
    _this->_internal_set_authorname(from._internal_authorname());
  }
  if (!from._internal_contents().empty()) {
    _this->_internal_set_contents(from._internal_contents());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void generic_message::CopyFrom(const generic_message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:info.generic_message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool generic_message::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* generic_message::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void generic_message::InternalSwap(generic_message* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authorname_, &other->_impl_.authorname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.contents_, &other->_impl_.contents_, arena);
}

::google::protobuf::Metadata generic_message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_info_2eproto_getter, &descriptor_table_info_2eproto_once,
      file_level_metadata_info_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace info
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
